"""Password in AccountModel

Revision ID: 333d1c139855
Revises: 94b033ff995a
Create Date: 2026-08-02 19:03:26.913734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333d1c139855'
down_revision: Union[str, Sequence[str], None] = '94b033ff995a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('password_hash', sa.String, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'password_hash')
    # ### end Alembic commands ###
