"""Init

Revision ID: 852698e0d951
Revises:
Create Date: 2026-07-28 22:38:10.825304

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "852698e0d951"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
