class DomainError(Exception): ...


class InvalidEmailError(DomainError): ...


class InvalidFullNameError(DomainError): ...


class AccountNotFoundError(DomainError): ...


class EmailAlreadyExistsError(DomainError): ...


class InvalidDatetimeError(DomainError): ...


class InvalidCredentialsError(DomainError): ...
